app/routes.rb, spec/integration_spec.rb
See https://github.com/mumuki/mumuki-classroom/pull/1.
=> Removed /api prefix

app/routes.rb, lib/classroom/guide_progress.rb, lib/mongo_collection.rb
=> Add filter by course and slug

app/routes.rb, lib/classroom/database.rb, lib/classroom/guide_progress.rb, lib/mongo_collection.rb
=> Only project last submission

app/routes.rb, lib/classroom/collection/exercise_student_progress.rb, lib/classroom/collection/guide_students_progress.rb, lib/classroom/collection/guides.rb, lib/classroom/collection/students.rb, spec/students_spec.rb
closes mumuki/mumuki-teacher-tools#175
=> Feature transfer student to other course

Gemfile, Gemfile.lock, app/routes.rb, lib/classroom.rb, lib/classroom/collection/exercise_student_progress.rb, spec/atheneum_spec.rb, spec/exercise_progress_spec.rb, spec/submission_spec.rb
Fix https://github.com/mumuki/mumuki-teacher-tools/issues/167
=> Inspections i18n

app/routes.rb
Setting root directory, so that sinatra can serve the version file
=> Serve version file

Gemfile, Gemfile.lock, README.md, lib/classroom.rb, lib/classroom/collections/people/students.rb, lib/classroom/reports.rb, lib/classroom/reports/formats.rb, lib/tasks/students.rake, spec/reports_spec.rb, spec/spec_helper.rb, spec/students_spec.rb
=> Feature reports

app/routes.rb, config.ru, config/database.yml, lib/classroom/database.rb, lib/classroom/event/course_changed.rb, lib/classroom/event/upsert_organization.rb, lib/classroom/event/user_changed.rb, lib/classroom/failed_submission.rb, lib/classroom/permissions_persistence/mongo.rb, migrations/migrate_uid.rb, migrations/migrate_update_student_last_assignment.rb, spec/comments_spec.rb, spec/courses_spec.rb, spec/database_spec.rb, spec/exercise_progress_spec.rb, spec/failed_submission_spec.rb, spec/followers_spec.rb, spec/guides_progress_spec.rb, spec/guides_spec.rb, spec/spec_helper.rb, spec/students_spec.rb, spec/submission_spec.rb, spec/teachers_spec.rb, spec/user_changed_spec.rb
* Reusing connections
* Making the connection thread safe
* Cleaning db in tests before running them
Fixes #81
=> Fix database connection optimization

README.md, config.ru, config/puma.rb, devstart
See https://github.com/mumuki/mumukit-platform/wiki/%5BMuBoot%5D-Standard-Mumuki-Platform-Boot-Process
=> Implementing `MuBoot`

app/routes/suggestions.rb, lib/classroom/models/suggestion.rb, spec/suggestions_spec.rb
Related to mumuki/mumuki-platform#282
=> Feature improve suggestions endpoint

app/routes/pagination.rb, lib/classroom/models/concerns/extensions.rb, lib/classroom/models/sorting/total_stats_sort_by.rb, spec/students_spec.rb
=> Fix search problems

app/routes/students.rb, lib/classroom/models/concerns/extensions.rb, lib/classroom/models/student.rb, migrations/drop_student_search_text_index.rb, spec/students_spec.rb
Added national_id with search support by this new field
Normalizing email, first_name and last_name
=> Feature add personal_id

Gemfile, Gemfile.lock, lib/classroom.rb, lib/classroom/models/user.rb, spec/messages_spec.rb
Merge after 
* https://github.com/mumuki/mumukit-login/pull/12
* https://github.com/mumuki/mumukit-platform/pull/10
* https://github.com/mumuki/mumuki-laboratory/pull/915
Also, update platform and login to tagged dependencies before merging
=> Feature platform 1

Gemfile, Gemfile.lock, app/routes.rb, app/routes/courses.rb, bin/console, lib/classroom.rb, lib/classroom/event/user_changed.rb, lib/classroom/models/course.rb, lib/classroom/models/organization.rb, lib/classroom/models/user.rb, lib/events.rb, spec/courses_spec.rb, spec/exercise_progress_spec.rb, spec/followers_spec.rb, spec/organization_spec.rb, spec/spec_helper.rb, spec/students_spec.rb
Related to https://github.com/mumuki/mumukit-platform/issues/12
=> Feature unified platform model

Gemfile, Gemfile.lock, app/routes.rb, app/routes/students.rb, lib/classroom/models/assignment.rb, lib/classroom/models/guide_progress.rb, lib/classroom/models/student.rb, spec/students_spec.rb
=> Issue#133 expose student transfer api

seed-central.js
At least in my machine it throws an exception with a syntax error on this line
=> Fixing seed syntax error

lib/classroom/models/exam.rb, spec/exams_spec.rb
Related to mumuki/mumuki-laboratory#1108.
=> add max submissions fields in exams

lib/classroom/models.rb, lib/classroom/models/exam.rb, lib/classroom/models/passing_criterion/none.rb, lib/classroom/models/passing_criterion/passed_exercises.rb, lib/classroom/models/passing_criterion/passing_criterion.rb, lib/classroom/models/passing_criterion/percentage.rb, spec/exams_spec.rb
Related to mumuki/mumuki-classroom#186.
=> Add passing grade

app/routes.rb, app/routes/courses.rb, app/routes/pagination.rb, app/routes/searching.rb, app/routes/students.rb, lib/classroom/models/reporting.rb, lib/classroom/models/searching.rb, lib/classroom/models/searching/guide_progress.rb, lib/classroom/models/sorting.rb, spec/guides_progress_spec.rb
Adding api support for https://github.com/mumuki/mumuki-classroom/pull/196
=> adding support for query operands

app/omniauth.rb, app/routes.rb
Related to mumuki/mumukit-login#23.
=> remove omniauth and unnecessary login logic

app/routes.rb, app/routes/errors.rb, spec/courses_spec.rb
Fixes #145
I suspect this was happening in certain environments (development only?) since there were green specs that covered that feature
=> Fixing error handlers - Fixes #145

lib/classroom/models/searching/guide_progress.rb, spec/guides_progress_spec.rb
=> New filtering criterias - Fixes #141

lib/mumuki/classroom/engine.rb, lib/mumuki/classroom/sinatra.rb, lib/mumuki/classroom/sinatra/courses.rb, lib/mumuki/classroom/sinatra/errors.rb, lib/mumuki/classroom/sinatra/exams.rb, lib/mumuki/classroom/sinatra/followers.rb, lib/mumuki/classroom/sinatra/guides.rb, lib/mumuki/classroom/sinatra/manual_evaluation.rb, lib/mumuki/classroom/sinatra/messages.rb, lib/mumuki/classroom/sinatra/notifications.rb, lib/mumuki/classroom/sinatra/organization.rb, lib/mumuki/classroom/sinatra/pagination.rb, lib/mumuki/classroom/sinatra/permissions.rb, lib/mumuki/classroom/sinatra/ping.rb, lib/mumuki/classroom/sinatra/searching.rb, lib/mumuki/classroom/sinatra/students.rb, lib/mumuki/classroom/sinatra/suggestions.rb, lib/mumuki/classroom/sinatra/teachers.rb, spec/spec_helper.rb
Este PR mergea a `feature-invitations-unification`, no a `master`.
=> Using modular style

app/routes/students.rb
Needed for https://github.com/mumuki/mumuki-classroom-ui/issues/226
=> Add all students endpoint

app/routes/students.rb
Enhancement needed for https://github.com/mumuki/mumuki-classroom-ui/issues/226
=> Add pagination to "all students" query

app/routes/courses.rb, app/routes/errors.rb, lib/classroom/models/organization.rb, spec/courses_spec.rb
=> Issue#170 validate orga exists on create course

lib/classroom/models/guide_progress.rb, spec/students_spec.rb
~(not) fixing #169~
I had to modify the `transfer` test a little, it was using the wrong query, so the `.all?(...)` always returned true but because it was always an empty array :smile_cat: 
Please review thoroughly, I'm not sure of anything about this PR. ¯\_(ツ)_/¯
=> Importing progresses only from the course's organization

app/routes.rb, app/routes/courses.rb, app/routes/students.rb, spec/students_spec.rb
This was requested here: https://github.com/mumuki/mumuki-classroom-ui/pull/231#discussion_r255946853.
I added the course to the report for good measure, too.
=> Feature add all students report

app/routes/students.rb
Resolves #173 
Merge after https://github.com/mumuki/mumuki-classroom-ui/pull/247
=> requiring janitor permissions for students endpoint

Gemfile, Gemfile.lock, app/routes/courses.rb, spec/permissions_diff_spec.rb
=> Updating mumukit-auth and mumukit-core and using admin permission

app/routes.rb, app/routes/exams.rb, app/routes/massive.rb
Review with mumuki/mumuki-laboratory#1373 and mumuki/mumuki-domain#60.
=> Notify only student diffs when adding or deleting users to exam

Gemfile, Gemfile.lock, lib/classroom/models/assignment.rb
Requires new mumukit-core at https://github.com/mumuki/mumukit-core/pull/17
=> Skipped and passed submissions are solved

lib/mumuki/classroom.rb, lib/mumuki/classroom/event/user_changed.rb, lib/mumuki/classroom/models.rb, lib/mumuki/classroom/models/concerns/course_member.rb, lib/mumuki/classroom/models/student.rb, lib/mumuki/classroom/models/teacher.rb, lib/mumuki/classroom/sinatra.rb, lib/mumuki/classroom/sinatra/courses.rb, lib/mumuki/classroom/sinatra/errors.rb, lib/mumuki/classroom/sinatra/massive.rb, lib/mumuki/classroom/sinatra/teachers.rb, lib/mumuki/events.rb, lib/tasks/mumuki/events.rake, spec/dummy/config/puma.rb, spec/spec_helper.rb, spec/students_spec.rb, spec/suggestions_spec.rb, spec/teachers_spec.rb, spec/user_changed_spec.rb
Requires: https://github.com/mumuki/mumuki-domain/pull/97
=> Remove useless nuntius events

lib/mumuki/classroom/event.rb, lib/mumuki/classroom/event/progress_transfer.rb, lib/mumuki/classroom/event/progress_transfer/base.rb, lib/mumuki/classroom/event/progress_transfer/copy.rb, lib/mumuki/classroom/event/progress_transfer/move.rb, lib/mumuki/classroom/models/assignment.rb, lib/mumuki/classroom/models/concerns/with_submission_process.rb, lib/mumuki/classroom/models/failed_submission.rb, lib/mumuki/classroom/models/guide_progress.rb, lib/mumuki/classroom/models/student.rb, lib/tasks/mumuki/progress_transfers.rake, spec/factories/student_factory.rb, spec/progress_transfer_spec.rb, spec/spec_helper.rb
We shouldn't merge this until we're done with progress separation!
=> Feature progress transfer

lib/mumuki/classroom/models.rb, lib/mumuki/classroom/models/certificate.rb, lib/mumuki/classroom/models/exam_authorization.rb, lib/mumuki/classroom/models/exam_authorization_request.rb
Add certificate model to allow saving backups now that we're adding support for account deletion
=> Add certificate model
